### ISSUE TITLE
txt data files?

### ISSUE THREAD

**Issue by ahopple** [COMPASS-DOE/TEMPESTX#2]
@bpbond how are the json files converted to txt files?

**Comment by bpbond** [comment]
Right now, using Licor's SoilFluxPro program.

**Comment by ahopple** [comment]
Could you show me how to do this next week? It looks like most of the recent measurements have not been converted from json files. Also, I think Steph transferred over the old TEMPESTX repo (that was originally within TEMPEST) to COMPASS. Is it alright if I move this repo to the COMPASS organization?

**Comment by bpbond** [comment]
Yes, definitely. And yes, it looks like she did—which I wasn't expecting. And yes, let's move this to COMPASS. I need to initiate that, but we should probably rename the one that Steph put in first.

**Comment by ahopple** [comment]
Sounds good. I just changed the old TEMPESTX name.
