### ISSUE TITLE
Thursday/Friday TEMPEST 3 msmts

### ISSUE THREAD

**Issue by bpbond** [COMPASS-DOE/TEMPESTX#9]
Check with @wilsonsj100 and @stephpenn1 -- was 7810 smart chamber downloaded after Thursday and Friday's TEMPEST GHG measurements?

**Comment by wilsonsj100** [comment]
I downloaded and put them on the google drive - sent an email about this this morning. :)

**Comment by bpbond** [comment]
😂 so you did. Sorry!

**Comment by wilsonsj100** [comment]
No problem - i could've uploaded here.... sorry!
